### ISSUE TITLE
TO-DO LIST

### ISSUE THREAD

**Issue by slawek87** [slawek87/geolocation-python#4]
- [x] Documentation on readthedocs.org.
- [x] API for https://developers.google.com/maps/documentation/distancematrix/
- [ ] A **VERSION** file.
- [ ] Add a code coverage badge.

Alexandre update this list with your ideas.
